ucrt64_c_compiler:             # [win]
  - ucrt64-gcc-toolchain       # [win]
ucrt64_cxx_compiler:           # [win]
  - ucrt64-gcc-toolchain       # [win]
ucrt64_fortran_compiler:       # [win]
  - ucrt64-gcc-toolchain       # [win]
# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:
  - win-64                     # [win]
#  - win-32                     # [win]
target_platform:
  - win-64                     # [win]
#  - win-32                     # [win]
