{% set version = "6.2.0" %}

package:
  name: gmp
  version: {{ version }}

source:
  fn: gmp-{{ version }}.tar.bz2
  url: https://gmplib.org/download/gmp/gmp-{{ version }}.tar.bz2
  sha256: f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gmp") }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make
  host:

test:
  requires:
    - {{ compiler('c') }}

  files:
    - test.c

  commands:
    - test -f ${PREFIX}/lib/libgmp.a        # [unix]
    - test -f ${PREFIX}/lib/libgmp.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgmp.so       # [linux]
    - test -f ${PREFIX}/lib/libgmpxx.a      # [unix]
    - test -f ${PREFIX}/lib/libgmpxx.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgmpxx.so     # [linux]

about:
  home: http://gmplib.org/
  license: GPL 2 and LGPL 3
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
