{% set version = "6.2.0" %}

package:
  name: gmp
  version: {{ version }}

source:
  url: https://gmplib.org/download/gmp/gmp-{{ version }}.tar.bz2
  sha256: f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea
  patches:
    # Patch taken from homebrew. https://raw.githubusercontent.com/Homebrew/formula-patches/c53834b4/gmp/6.2.0-arm.patch
    # Originially from https://gmplib.org/list-archives/gmp-bugs/2020-July/004837.html
    - 6.2.0-arm.patch  # [osx and arm64]

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gmp") }}

requirements:
  build:
    - libtool  # [unix]
    - autoconf  # [osx and arm64]
    - automake  # [osx and arm64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make
  host:

test:
  requires:
    - {{ compiler('c') }}

  files:
    - test.c

  commands:
    - test -f ${PREFIX}/lib/libgmp.a        # [unix]
    - test -f ${PREFIX}/lib/libgmp.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgmp.so       # [linux]
    - test -f ${PREFIX}/lib/libgmpxx.a      # [unix]
    - test -f ${PREFIX}/lib/libgmpxx.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgmpxx.so     # [linux]

about:
  home: http://gmplib.org/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
