{% set version = "6.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set am_version = "1.15" %} #  keep synchronized with build.sh

package:
  name: gmp
  version: {{ version }}

source:
  url: https://gmplib.org/download/gmp/gmp-{{ version }}.tar.bz2
  sha256: eae9326beb4158c386e39a356818031bd28f3124cf915f8c5b1dc4c7a36b4d7c
  patches:
    - 0000-Avoid-the-x18-register.patch

build:
  number: 4
  skip: true  # [not win]
  run_exports:
    # excellent, even across major ver:
    #  https://abi-laboratory.pro/tracker/timeline/gmp/
    - {{ pin_subpackage("gmp") }}

requirements:
  build:              
    - gnuconfig
    - {{ compiler('m2w64_c') }}         # [win]
    - {{ compiler('m2w64_cxx') }}       # [win]
    - {{posix}}m4
    - {{posix}}make
    - {{posix}}patch
    - posix                     # [win]
    - {{posix}}autoconf                   # [win]
    - {{posix}}automake{{ am_version }}   # [win]
    - {{posix}}libtool                    # [win]
    - {{posix}}pkg-config                    
    - {{posix}}automake-wrapper
    - {{posix}}sed

  host:

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test.c

  commands:
    - test -f ${PREFIX}/lib/libgmp.a        # [unix]
    - test -f ${PREFIX}/lib/libgmp.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgmp.so       # [linux]
    - test -f ${PREFIX}/lib/libgmpxx.a      # [unix]
    - test -f ${PREFIX}/lib/libgmpxx.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgmpxx.so     # [linux]
    - dir /s %PREFIX%\Library\ # [win]
    - if not exist %PREFIX%\Library\mingw-w64\bin\libgmp-10.dll exit /b 1  # [win]
    - if not exist %PREFIX%\Library\mingw-w64\bin\libgmpxx-4.dll exit /b 1  # [win]
    - if not exist %PREFIX%\Library\mingw-w64\include\gmp.h exit /b 1  # [win]
    - if not exist %PREFIX%\Library\mingw-w64\lib\libgmp.a exit /b 1  # [win]


about:
  home: https://gmplib.org/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.
  dev_url: https://gmplib.org/repo/
  doc_url: https://gmplib.org/manual/

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
