{% set name = "gmp" %}
{% set version = "6.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set am_version = "1.15" %} #  keep synchronized with build.sh

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gmplib.org/download/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: ac28211a7cfb609bae2e2c8d6058d66c8fe96434f740cf6fe2e47b000d1c20cb

build:
  number: 0
  run_exports:
    # excellent, even across major ver:
    #  https://abi-laboratory.pro/tracker/timeline/gmp/
    - {{ pin_subpackage("gmp") }}

requirements:
  build:
    - {{ compiler('c') }}                 # [unix]
    - {{ compiler('cxx') }}               # [unix]
    - gnuconfig                           # [unix]
    - m4                                  # [unix]
    - make                                # [unix]
    - m2w64-toolchain                     # [win]
    # m2-autoconf includes m2-m4 for win
    - {{posix}}autoconf                   # [win]
    - {{posix}}automake-wrapper           # [win]
    - {{posix}}automake{{ am_version }}   # [win]
    - {{posix}}libtool                    # [win]
    - posix                               # [win]
    - {{posix}}pkg-config

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test.c
  commands:
    - test -f ${PREFIX}/lib/libgmp.a        # [unix]
    - test -f ${PREFIX}/lib/libgmp.dylib    # [osx]
    - test -f ${PREFIX}/lib/libgmp.so       # [linux]
    - test -f ${PREFIX}/lib/libgmpxx.a      # [unix]
    - test -f ${PREFIX}/lib/libgmpxx.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgmpxx.so     # [linux]
    # tests for win64 are included to run_test.bat

about:
  home: https://gmplib.org/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_family: Other
  license_file:
    - COPYING.LESSERv3
    - COPYINGv2
    - COPYINGv3
  summary: The GNU multiprecision library.
  description: |
    GNU MP is a portable library written in C for arbitrary precision arithmetic on integers,
    rational numbers, and floating-point numbers.
    It aims to provide the fastest possible arithmetic for all applications
    that need higher precision than is directly supported by the basic C types.
  dev_url: https://gmplib.org/repo/
  doc_url: https://gmplib.org/manual/

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
