travis:
  secure:
    BINSTAR_TOKEN: QUrIh3q7yOTyMRxHkVXw7UlD/1QLxy5wUKCol9Cq2LBmWiN6euL5fLZEwSkqF+cEUfwEjGNltkSkTHUI5it2DfmH8q97YswHjtXHQC7XZ5zC45m7z8UqT4JX/wwHwW45kmNM2tS4k4M5brLelCWkb0xGuQb7ceyn2UbaIzRhXfy3BZVgIw37Nx9Z0Uzm3hYfCskiczrm5ewHuihL9lhZv+1e76XURHL/QfKezGDVPD7g6oPHF/QtQjkxe0/9iwLJcbVa9xlNwjJeuLhuW8mQSrhZHogwcSR0O6dWgy5gv7fzGzJv3fBc3ry7L5U6oCNdZj9TXjkNvCMnGpgKDFuf//q06NfMqLdTHTsr+gLslKIDMFBZFmHqNtNLyLy7gsDcHv1gh2Avc4s/sj0JS+57ieet4pClc8fu4BLabYca4vHf7FQt4ASv7nUs2oWuAhUHfa88geWZfT52eLLqjffhhsTdnJUUI/v/eEYvTsOpdqdrOg1ozKAe2sG3mXGSS8pGir06EheRJRc1BDAzyF5qkVYr4vPecbZDDlt+CSq1bMkiiy+j8hRwp6sDNKGcyTP7sMhqM53CZmB0SCy+jQkAvinMxink/YWIzn2Bp5Xl0G9wT52grBbsTMUX3dlD3ZjkrNUzb5hSlmYCZOx6za8s7k62orzIqU21HyGGTIsZJNY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
